import { PageHeader } from '@/components/page-header';
import { api, humanize } from '@/lib/api';

export const dynamic = 'force-dynamic';
export default async function SettingsPage() {
  const settings = await api<Record<string, any>>('/settings', {});
  const weights = settings.scoring?.weights ?? {};
  const thresholds = settings.scoring?.thresholds ?? {};
  const xCostControls = settings.integrations?.xCostControls ?? {};
  return <><PageHeader eyebrow="Safe runtime view" title="Settings" /><div className="grid gap-5 lg:grid-cols-2"><section className="rounded-xl border border-slate-200 bg-white p-6"><h2 className="font-semibold">Enabled sources</h2><div className="mt-4 flex flex-wrap gap-2">{(settings.enabledSources ?? []).map((source: string) => <span key={source} className="rounded-full bg-emerald-100 px-3 py-1 text-sm text-emerald-800">{source}</span>)}</div><h2 className="mt-8 font-semibold">Integrations</h2><dl className="mt-4 space-y-2 text-sm"><div className="flex justify-between"><dt className="text-slate-500">Ollama model</dt><dd>{settings.integrations?.ollama?.model ?? '—'}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Minimum LLM confidence</dt><dd>{Math.round(Number(settings.integrations?.ollama?.minimumConfidence ?? 0) * 100)}%</dd></div><div className="flex justify-between"><dt className="text-slate-500">Telegram</dt><dd>{settings.integrations?.telegram?.configured ? 'Configured' : 'Needs credentials'}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Delivery mode</dt><dd>{humanize(settings.integrations?.telegram?.deliveryMode)}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Images per Telegram post</dt><dd>{settings.integrations?.telegram?.maxImages ?? '—'}</dd></div></dl><h2 className="mt-8 font-semibold">X credit controls</h2><dl className="mt-4 space-y-2 text-sm"><div className="flex justify-between"><dt className="text-slate-500">Daily post-read cap</dt><dd>{xCostControls.dailyPostBudget ?? '—'}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Queries per cycle</dt><dd>{xCostControls.queriesPerRun ?? '—'}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Maximum results/query</dt><dd>{xCostControls.maxResults ?? '—'}</dd></div></dl></section><section className="rounded-xl border border-slate-200 bg-white p-6"><h2 className="font-semibold">Deterministic scoring</h2><div className="mt-4 grid grid-cols-2 gap-3">{Object.entries(weights).map(([name, value]) => <div key={name} className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-500">{humanize(name)}</p><p className="mt-1 font-mono">{Math.round(Number(value) * 100)}%</p></div>)}</div><h3 className="mt-6 text-sm font-semibold">Thresholds</h3><div className="mt-3 grid grid-cols-2 gap-3">{Object.entries(thresholds).map(([name, value]) => <div key={name} className="flex justify-between rounded-lg border border-slate-200 px-3 py-2 text-sm"><span>{humanize(name)}</span><span className="font-mono">{String(value)}</span></div>)}</div></section></div></>;
}
