import Link from 'next/link';
import { PageHeader } from '@/components/page-header';
import { api, formatTime, humanize, telegramPlainText } from '@/lib/api';
import { Publication } from '@/types';

export const dynamic = 'force-dynamic';
export default async function PublicationsPage() {
  const publications = await api<Publication[]>('/publications', []);
  return <><PageHeader eyebrow="Exact outgoing content" title="Telegram outbox" /><div className="space-y-5">{publications.map((publication) => <article key={publication.id} className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 bg-slate-50 px-5 py-3 text-sm"><div className="flex items-center gap-3"><span className="font-semibold">{humanize(publication.type)}</span><span className={`rounded-full px-2.5 py-1 text-xs ${publication.status === 'SENT' ? 'bg-emerald-100 text-emerald-800' : publication.status === 'FAILED' ? 'bg-red-100 text-red-800' : 'bg-amber-100 text-amber-800'}`}>{humanize(publication.status)}</span>{publication.scoreAtPublication && <span className="font-mono text-slate-500">Score {Math.round(publication.scoreAtPublication)}</span>}</div><time className="text-xs text-slate-500">{formatTime(publication.publishedAt ?? publication.createdAt)}</time></header><div className="grid gap-5 p-5 lg:grid-cols-[minmax(0,1fr)_240px]"><div><pre className="whitespace-pre-wrap break-words rounded-xl bg-slate-950 p-5 font-sans text-sm leading-6 text-slate-100">{telegramPlainText(publication.content)}</pre>{Boolean(publication.mediaUrls?.length) && <div className="mt-4 grid gap-3 sm:grid-cols-2">{publication.mediaUrls!.map((url) => <a key={url} href={url} target="_blank" rel="noreferrer" className="overflow-hidden rounded-xl border border-slate-200"><img src={url} alt="Image delivered with this Telegram publication" className="h-48 w-full object-cover" /></a>)}</div>}</div><aside className="text-sm"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Associated trend</p><p className="mt-2">{publication.trend ? <Link className="font-medium hover:text-orange-600" href={`/trends/${publication.trend.id}`}>{publication.trend.canonicalTitle}</Link> : 'Multi-trend edition'}</p><p className="mt-5 text-xs text-slate-500">This preview is generated from the exact text and delivered images stored for Telegram. Telegram applies bold text and source links from the stored HTML.</p></aside></div></article>)}{!publications.length && <p className="rounded-xl border border-dashed bg-white p-10 text-center text-slate-500">No Telegram messages have been queued yet. Eligible breakouts and scheduled editions will appear here with their delivery status.</p>}</div></>;
}
